version: '2'

volumes:
  mysql:

networks:
  backend:

services:
  mysqldb:
    image: mysql:5.7.17
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: workshop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      backend:

  db.migration:
    image: db.migration
    container_name: db.migration
    networks:
      backend:

  config:
    image: config
    container_name: config
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    ports:
      - "8888:8888"
    networks:
      backend:

  discovery:
    image: discovery
    container_name: discovery
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    ports:
      - "8761:8761"
    networks:
      backend:

  gateway:
    image: gateway
    container_name: gateway
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    ports:
      - "8090:9000"
    networks:
      backend:

  security:
    image: security
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend:

  business:
    image: business
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend:

  doctor:
    image: doctor
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend: