version: '2'

volumes:
  mysql:
  elasticsearch_volume:

networks:
  backend:

services:
  mysqldb:
    image: mysql:5.7.17
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: workshop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      backend:

  db.migration:
    image: db.migration
    container_name: db.migration
    networks:
      backend:

  config:
    image: config
    container_name: config
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    ports:
      - "8888:8888"
    networks:
      backend:

  discovery:
    image: discovery
    container_name: discovery
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    ports:
      - "8761:8761"
    networks:
      backend:

  security:
    image: security
    container_name: security
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend:

  business:
    image: business
    container_name: business
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend:

  doctor:
    image: doctor
    container_name: doctor
    ports:
      - 8081:8080
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend:

  elasticsearch:
    image: elasticsearch:5.1.2
    restart: always
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    networks:
      backend:

  logstash:
    image: logstash
    restart: always
    command: logstash -f /config-dir/logstash.conf
    container_name: logstash
    ports:
      - 5044:5044
      - 4560:4560
    links:
      - elasticsearch
    networks:
      backend:

  kibana:
    image: kibana:5.1.2
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
    networks:
      backend: