version: '2'

volumes:
  mysql:

networks:
  backend:

services:
  mysqldb:
    image: mysql:5.7.17
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: workshop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      backend:

  db.migration:
    image: db.migration
    container_name: db.migration
    networks:
      backend:

  security:
    image: security
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend:
    ports:
      - "9000:8080"

  business:
    image: business
    environment:
      - JAVA_OPTS=-Xms200m -Xmx400m
    networks:
      backend:
    ports:
      - "9001:8080"
